import { ScrapedLead } from './storage';

export const INITIAL_SCRAPED_LEADS: ScrapedLead[] = [
  {
    "id": "0cb840e5",
    "storeName": "Forza Motors",
    "city": "Paulínia",
    "phone": "(19) 2221-5570",
    "email": "contato@forzamotor.com.br",
    "link": "https://forzamotor.com.br/",
    "instagram": "https://www.instagram.com/forzamotors",
    "status": "Não contatado",
    "score": 20,
    "createdAt": "2026-07-21T18:51:02.047Z"
  },
  {
    "id": "c751752f",
    "storeName": "Luvicar Veículos",
    "city": "Paulínia",
    "phone": "(19) 3217-3287",
    "email": "contato@luvicar.com.br",
    "link": "https://luvicar.com.br/",
    "instagram": "https://www.instagram.com/luvicarveiculos",
    "status": "Não contatado",
    "score": 20,
    "createdAt": "2026-07-21T18:51:02.048Z"
  },
  {
    "id": "f5507951",
    "storeName": "Azzurra Veículos",
    "city": "Paulínia",
    "phone": "",
    "email": "contato@azzurraveiculos.com.br",
    "link": "https://www.azzurraveiculos.com.br/",
    "instagram": "https://www.instagram.com/azzurraveiculos",
    "status": "Não contatado",
    "score": 20,
    "createdAt": "2026-07-21T18:51:02.048Z"
  },
  {
    "id": "9e9af0f4",
    "storeName": "Waguinho Veículos",
    "city": "Paulínia",
    "phone": "(19) 3844-0297",
    "email": "contato@waguinhoveiculos.com.br",
    "link": "https://waguinhoveiculos.com.br/",
    "instagram": "https://www.instagram.com/waguinhoveiculos",
    "status": "Não contatado",
    "score": 20,
    "createdAt": "2026-07-21T18:51:02.048Z"
  },
  {
    "id": "3cecd31c",
    "storeName": "Autodon",
    "city": "Paulínia",
    "phone": "",
    "email": "contato@autodon.com.br",
    "link": "https://autodon.com.br/",
    "instagram": "https://www.instagram.com/autodon",
    "status": "Não contatado",
    "score": 20,
    "createdAt": "2026-07-21T18:51:02.049Z"
  },
  {
    "id": "8bc7f2b2",
    "storeName": "ABA Veículos",
    "city": "Paulínia",
    "phone": "(19) 99927-7685",
    "email": "contato@abaveiculos.com.br",
    "link": "https://abaveiculos.com.br/",
    "instagram": "https://www.instagram.com/abaveiculos",
    "status": "Não contatado",
    "score": 20,
    "createdAt": "2026-07-21T18:51:02.049Z"
  },
  {
    "id": "bf74b749",
    "storeName": "Ricavel Multimarcas",
    "city": "Paulínia",
    "phone": "",
    "email": "contato@ricavelmultimarcas.com",
    "link": "https://ricavelmultimarcas.com/",
    "instagram": "https://www.instagram.com/ricavelmultimarcas",
    "status": "Não contatado",
    "score": 20,
    "createdAt": "2026-07-21T18:51:02.049Z"
  },
  {
    "id": "f247c0d3",
    "storeName": "Mv Veículos",
    "city": "Paulínia",
    "phone": "",
    "email": "contato@mvveiculos.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/mvveiculos",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:51:02.049Z"
  },
  {
    "id": "e9d52f61",
    "storeName": "Miami Veículos",
    "city": "Paulínia",
    "phone": "(19) 97412-0233",
    "email": "contato@miamiveiculos.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/miamiveiculos",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:51:02.049Z"
  },
  {
    "id": "f96a55ee",
    "storeName": "Cássio Veículos",
    "city": "Paulínia",
    "phone": "(19) 3874-4002",
    "email": "contato@cassioveiculos.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/cassioveiculos",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:51:02.049Z"
  },
  {
    "id": "ec8a2639",
    "storeName": "Alpha Veículos",
    "city": "Valinhos",
    "phone": "(19) 98155-9204",
    "email": "contato@alphaveiculos.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/alphaveiculos",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:06:56.874Z"
  },
  {
    "id": "be97cf6b",
    "storeName": "EA Motors",
    "city": "Valinhos",
    "phone": "",
    "email": "contato@eamotors.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/eamotors",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "564d14bd",
    "storeName": "Zacar Veículos",
    "city": "Valinhos",
    "phone": "(19) 99209-5626",
    "email": "contato@zacarveiculos.com.br",
    "link": "https://zacarveiculos.com.br/",
    "instagram": "https://www.instagram.com/zacarveiculos",
    "status": "Não contatado",
    "score": 20,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "5c91bbf3",
    "storeName": "Sandro Veículos",
    "city": "Valinhos",
    "phone": "",
    "email": "contato@sandroveiculosvalinhos.com.br",
    "link": "https://sandroveiculosvalinhos.com.br/",
    "instagram": "https://www.instagram.com/sandroveiculos",
    "status": "Não contatado",
    "score": 20,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "9daa6a21",
    "storeName": "Visual Veículos",
    "city": "Valinhos",
    "phone": "",
    "email": "contato@visualveiculos.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/visualveiculos",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "16b248ef",
    "storeName": "Makine Motors",
    "city": "Valinhos",
    "phone": "(19) 97411-5616",
    "email": "contato@makinemotors.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/makinemotors",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "72d15cfb",
    "storeName": "Concessionária Codive",
    "city": "Valinhos",
    "phone": "",
    "email": "contato@codivechevroletvalinhos.com.br",
    "link": "https://www.codivechevroletvalinhos.com.br/",
    "instagram": "https://www.instagram.com/concessionariacodive",
    "status": "Não contatado",
    "score": 20,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "d82751d4",
    "storeName": "Destaque Motors",
    "city": "Valinhos",
    "phone": "",
    "email": "contato@destaquemotors.com.br",
    "link": "https://destaquemotors.com.br/",
    "instagram": "https://www.instagram.com/destaquemotors",
    "status": "Não contatado",
    "score": 20,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "5879877b",
    "storeName": "Vaapty Valinhos",
    "city": "Valinhos",
    "phone": "",
    "email": "contato@vaaptyvalinhos.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/vaaptyvalinhos",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "06051e3b",
    "storeName": "Sabini Motors",
    "city": "Valinhos",
    "phone": "",
    "email": "contato@sabinimotors.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/sabinimotors",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "f6d64644",
    "storeName": "Font Car Veículos",
    "city": "Valinhos",
    "phone": "",
    "email": "contato@fontcarveiculos.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/fontcarveiculos",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "1671c7de",
    "storeName": "Julio Ferreira Veículos",
    "city": "Valinhos",
    "phone": "",
    "email": "contato@julioferreiraveiculos.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/julioferreiraveiculos",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "e9c7f1f6",
    "storeName": "Will Motors",
    "city": "Valinhos",
    "phone": "",
    "email": "contato@willmotors.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/willmotors",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "487f18f1",
    "storeName": "Hypecar Veículos",
    "city": "Valinhos",
    "phone": "(19) 99741-2895",
    "email": "contato@hypecarveiculos.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/hypecarveiculos",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "1367f3b8",
    "storeName": "Destaque Valinhos",
    "city": "Valinhos",
    "phone": "",
    "email": "contato@destaquevalinhos.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/destaquevalinhos",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "70f66132",
    "storeName": "MD Motors",
    "city": "Valinhos",
    "phone": "",
    "email": "contato@mdmotors.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/mdmotors",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "5220c69e",
    "storeName": "Denilson Veículos",
    "city": "Valinhos",
    "phone": "(19) 97402-2240",
    "email": "contato@denilsonveiculos.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/denilsonveiculos",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "a9c3f4ed",
    "storeName": "Movva Veículos",
    "city": "Valinhos",
    "phone": "",
    "email": "contato@movvaveiculos.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/movvaveiculos",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "ce80719d",
    "storeName": "Independência Veículos",
    "city": "Valinhos",
    "phone": "(19) 3871-3180",
    "email": "contato@independenciaveiculos.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/independenciaveiculos",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "70104d66",
    "storeName": "Faccini Veículos",
    "city": "Valinhos",
    "phone": "(19) 99180-0084",
    "email": "contato@facciniveiculos.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/facciniveiculos",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "a1a26670",
    "storeName": "Chevrolet Codive",
    "city": "Valinhos",
    "phone": "",
    "email": "contato@chevroletcodive.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/chevroletcodive",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "e31701d8",
    "storeName": "Alvorada Automóveis",
    "city": "Nova Odessa",
    "phone": "(19) 2221-7298",
    "email": "atendimento@alvoradaautomoveisno.com.br",
    "link": "https://alvoradaautomoveisno.com.br/",
    "instagram": "https://www.instagram.com/alvorada_automoveis/",
    "status": "Não contatado",
    "score": 20,
    "createdAt": "2026-07-21T18:05:17.062Z"
  },
  {
    "id": "39d9b958",
    "storeName": "MK Veículos",
    "city": "Nova Odessa",
    "phone": "",
    "email": "contato@mkveiculos.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/mkveiculosno/",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:05:17.062Z"
  },
  {
    "id": "ee968c28",
    "storeName": "Pantera Veículos",
    "city": "Nova Odessa",
    "phone": "(19)3466-2917",
    "email": "contato@panteraveiculos.com.br",
    "link": "https://www.panteraveiculos.com.br/",
    "instagram": "https://www.instagram.com/pantera.veiculos/",
    "status": "Não contatado",
    "score": 20,
    "createdAt": "2026-07-21T18:05:17.062Z"
  },
  {
    "id": "2fb4b6a4",
    "storeName": "SR Veículos",
    "city": "Nova Odessa",
    "phone": "",
    "email": "contato@srveiculos.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/sr_veiculos/",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:05:17.062Z"
  },
  {
    "id": "ab66cfbd",
    "storeName": "Nova Odessa Veículos",
    "city": "Nova Odessa",
    "phone": "",
    "email": "contato@noveiculos.com.br",
    "link": "https://noveiculos.com.br/",
    "instagram": "https://www.instagram.com/novaodessaveiculos",
    "status": "Não contatado",
    "score": 20,
    "createdAt": "2026-07-21T18:05:17.062Z"
  },
  {
    "id": "2c1ceb41",
    "storeName": "GB Car Veículos",
    "city": "Nova Odessa",
    "phone": "",
    "email": "contato@gbcarveiculos.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/gbcar_veiculos2015/",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:05:17.062Z"
  },
  {
    "id": "718b7042",
    "storeName": "Ampelio Multimarcas",
    "city": "Nova Odessa",
    "phone": "",
    "email": "contato@ampeliomultimarcas.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/ampeliomultimarcas/",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:05:17.063Z"
  },
  {
    "id": "5edf5a85",
    "storeName": "Nova Odessa Carros & Motos",
    "city": "Nova Odessa",
    "phone": "(19)9 7407-4795",
    "email": "contato@novaodessacarrosmotos.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/novaodessaveiculos/",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:05:17.063Z"
  },
  {
    "id": "43456ddf",
    "storeName": "Jazz Veículos",
    "city": "Nova Odessa",
    "phone": "",
    "email": "contato@jazzveiculos.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/jazzveiculos/",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:05:17.063Z"
  },
  {
    "id": "0cf929df",
    "storeName": "Vessa Chevrolet",
    "city": "Nova Odessa",
    "phone": "",
    "email": "contato@vessachevrolet.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/vessa.veiculos/",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:05:17.063Z"
  },
  {
    "id": "1c6012a2",
    "storeName": "Paschoalin Motors",
    "city": "Nova Odessa",
    "phone": "",
    "email": "contato@paschoalinmotors.com.br",
    "link": "https://paschoalinmotors.com.br/",
    "instagram": "https://www.instagram.com/paschoalinmotors",
    "status": "Não contatado",
    "score": 20,
    "createdAt": "2026-07-21T18:05:17.063Z"
  },
  {
    "id": "ba7fecc5",
    "storeName": "DZM Automóveis",
    "city": "Nova Odessa",
    "phone": "(19) 3090-3345",
    "email": "contato@dzmautomoveis.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/dzm.automoveis/",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:05:17.063Z"
  },
  {
    "id": "7dfb64f4",
    "storeName": "Mônaco Veículos",
    "city": "Nova Odessa",
    "phone": "0800 000 3148",
    "email": "contato@monacoveiculos.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/monacoveiculosnorte/",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:05:17.063Z"
  },
  {
    "id": "09c72931",
    "storeName": "Conseg Veículos",
    "city": "Nova Odessa",
    "phone": "",
    "email": "contato@consegveiculos.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/consegveiculos/",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:05:17.063Z"
  },
  {
    "id": "449f1432",
    "storeName": "Rika Motors",
    "city": "Nova Odessa",
    "phone": "",
    "email": "contato@rikamotors.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/rikamotors/",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:05:17.063Z"
  },
  {
    "id": "489693c6",
    "storeName": "Agência de Carros",
    "city": "Nova Odessa",
    "phone": "",
    "email": "contato@agenciadecarros.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/ousadiaveiculos/",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:05:17.063Z"
  },
  {
    "id": "3f1dc12f",
    "storeName": "Prime Car",
    "city": "Nova Odessa",
    "phone": "",
    "email": "contato@primecar.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/primecar777/",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:05:17.063Z"
  },
  {
    "id": "86d8edaf",
    "storeName": "DNA Veículos",
    "city": "Nova Odessa",
    "phone": "(31) 98467",
    "email": "contato@dnaveiculos.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/p/DXbyo9YEQPm/",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:05:17.063Z"
  },
  {
    "id": "2b5c64b2",
    "storeName": "Fião Veículos",
    "city": "Nova Odessa",
    "phone": "",
    "email": "contato@fiaoveiculos.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/fiaoveiculos/",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:05:17.063Z"
  },
  {
    "id": "d1b90289",
    "storeName": "Altomani Multimarcas",
    "city": "Hortolândia",
    "phone": "",
    "email": "contato@altomanimultimarcas.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/altomanimultimarcas/",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:02:58.483Z"
  },
  {
    "id": "80daf1d4",
    "storeName": "Nobre Multimarcas",
    "city": "Hortolândia",
    "phone": "",
    "email": "contato@nobremultimarcas.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/reel/DEYJFXEPWN5/",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:02:58.484Z"
  },
  {
    "id": "c0a844be",
    "storeName": "Única Veículos",
    "city": "Hortolândia",
    "phone": "(19) 3504-8300 / 3909-0182",
    "email": "contato@unicaveiculos.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/unica.veiculos/",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:02:58.484Z"
  },
  {
    "id": "f129a9a2",
    "storeName": "Neri Veiculos",
    "city": "Hortolândia",
    "phone": "",
    "email": "contato@neriveiculoshortolandia.com.br",
    "link": "https://neriveiculoshortolandia.com.br/",
    "instagram": "https://www.instagram.com/neriveiculos_hortolandia/",
    "status": "Não contatado",
    "score": 20,
    "createdAt": "2026-07-21T18:02:58.484Z"
  },
  {
    "id": "b08304c7",
    "storeName": "Junior Cardoso Vehicles",
    "city": "Hortolândia",
    "phone": "",
    "email": "contato@juniorcardosovehicles.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/reel/DNbV-D2uUdp/",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:02:58.484Z"
  },
  {
    "id": "6b675613",
    "storeName": "Roberto Veículos",
    "city": "Hortolândia",
    "phone": "",
    "email": "contato@robertoveiculos.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/robertoveiculos.1/",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:02:58.484Z"
  },
  {
    "id": "80ee5085",
    "storeName": "Mais Veículos",
    "city": "Hortolândia",
    "phone": "",
    "email": "contato@maisveiculos.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/maisveiculos_hortolandia/",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:02:58.484Z"
  },
  {
    "id": "3ebe77e2",
    "storeName": "Ockner Motors",
    "city": "Hortolândia",
    "phone": "",
    "email": "contato@ocknermotors.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/ocknermotors/",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:02:58.484Z"
  },
  {
    "id": "1595ad8b",
    "storeName": "A3 Veículos",
    "city": "Hortolândia",
    "phone": "",
    "email": "contato@a3veiculosoficial.com.br",
    "link": "https://a3veiculosoficial.com.br/",
    "instagram": "https://www.instagram.com/a3veiculos",
    "status": "Não contatado",
    "score": 20,
    "createdAt": "2026-07-21T18:02:58.484Z"
  },
  {
    "id": "cacf71b5",
    "storeName": "Loja de Veículos",
    "city": "Hortolândia",
    "phone": "(19) 99119-7060",
    "email": "contato@lojadeveiculos.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/reel/DRkyYSOEUt1/",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:02:58.484Z"
  },
  {
    "id": "5c53d494",
    "storeName": "N5N Veículos",
    "city": "Hortolândia",
    "phone": "",
    "email": "contato@n5nveiculos.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/n5nveiculos/",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:02:58.484Z"
  },
  {
    "id": "060576cf",
    "storeName": "Vaapty Hortolândia",
    "city": "Hortolândia",
    "phone": "",
    "email": "contato@vaaptyhortolandia.com.br",
    "link": "",
    "instagram": "https://www.instagram.com/vaaptyhortolandia/",
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:02:58.484Z"
  }
];
