import type { ScrapedLead } from "./storage";

export const INITIAL_SCRAPED_LEADS: any[] = [
  {
    "id": "0cb840e5",
    "storeName": "Forza Motors",
    "city": "Paulínia",
    "phone": "(19) 2221-5570",
    "email": "",
    "link": "https://forzamotor.com.br/",
    "instagram": "https://www.instagram.com/forzamotorsbr",
    "followers": 2993,
    "status": "Não contatado",
    "score": 63,
    "createdAt": "2026-07-21T18:51:02.047Z"
  },
  {
    "id": "c751752f",
    "storeName": "Luvicar Veículos",
    "city": "Paulínia",
    "phone": "(19) 3217-3287",
    "email": "",
    "link": "https://luvicar.com.br/",
    "instagram": "https://www.instagram.com/luvicarveiculos",
    "followers": 6883,
    "status": "Não contatado",
    "score": 86,
    "createdAt": "2026-07-21T18:51:02.048Z"
  },
  {
    "id": "f5507951",
    "storeName": "Azzurra Veículos",
    "city": "Paulínia",
    "phone": "",
    "email": "",
    "link": "https://www.azzurraveiculos.com.br/",
    "instagram": "https://www.instagram.com/azzurraveiculos",
    "followers": 50231,
    "status": "Não contatado",
    "score": 100,
    "createdAt": "2026-07-21T18:51:02.048Z"
  },
  {
    "id": "9e9af0f4",
    "storeName": "Waguinho Veículos",
    "city": "Paulínia",
    "phone": "(19) 3844-0297",
    "email": "",
    "link": "https://waguinhoveiculos.com.br/",
    "instagram": "https://www.instagram.com/waguinhoveiculos",
    "followers": 1310,
    "status": "Não contatado",
    "score": 48,
    "createdAt": "2026-07-21T18:51:02.048Z"
  },
  {
    "id": "3cecd31c",
    "storeName": "Autodon",
    "city": "Paulínia",
    "phone": "",
    "email": "",
    "link": "https://autodon.com.br/",
    "instagram": "https://www.instagram.com/autodon",
    "followers": 61787,
    "status": "Não contatado",
    "score": 100,
    "createdAt": "2026-07-21T18:51:02.049Z"
  },
  {
    "id": "8bc7f2b2",
    "storeName": "ABA Veículos",
    "city": "Paulínia",
    "phone": "(19) 99927-7685",
    "email": "",
    "link": "https://abaveiculos.com.br/",
    "instagram": "https://www.instagram.com/abaveiculos",
    "followers": 4936,
    "status": "Não contatado",
    "score": 76,
    "createdAt": "2026-07-21T18:51:02.049Z"
  },
  {
    "id": "bf74b749",
    "storeName": "Ricavel Multimarcas",
    "city": "Paulínia",
    "phone": "",
    "email": "",
    "link": "https://ricavelmultimarcas.com/",
    "instagram": "https://www.instagram.com/ricavelmultimarcas",
    "followers": 2262,
    "status": "Não contatado",
    "score": 58,
    "createdAt": "2026-07-21T18:51:02.049Z"
  },
  {
    "id": "f247c0d3",
    "storeName": "Mv Veículos",
    "city": "Paulínia",
    "phone": "(19) 3874-1234",
    "email": "",
    "link": "https://mvveiculos.com.br/",
    "instagram": "https://www.instagram.com/mvveiculos",
    "followers": 20000,
    "status": "Não contatado",
    "score": 100,
    "createdAt": "2026-07-21T18:51:02.049Z"
  },
  {
    "id": "e9d52f61",
    "storeName": "Miami Veículos",
    "city": "Paulínia",
    "phone": "(19) 97412-0233",
    "email": "vendas@miamiveiculos.com.br",
    "link": "https://miamiveiculos.com.br/",
    "instagram": "https://www.instagram.com/miamiveiculos",
    "followers": 311,
    "status": "Não contatado",
    "score": 34,
    "createdAt": "2026-07-21T18:51:02.049Z"
  },
  {
    "id": "f96a55ee",
    "storeName": "Cássio Veículos",
    "city": "Paulínia",
    "phone": "(19) 3874-4002",
    "email": "",
    "link": "https://cassioautomoveis.com.br/",
    "instagram": "https://www.instagram.com/cassioveiculos",
    "followers": 35,
    "status": "Não contatado",
    "score": 24,
    "createdAt": "2026-07-21T18:51:02.049Z"
  },
  {
    "id": "ec8a2639",
    "storeName": "Alpha Veículos",
    "city": "Valinhos",
    "phone": "(19) 98155-9204",
    "email": "",
    "link": "https://www.alphaveiculosvalinhos.com.br/",
    "instagram": "https://www.instagram.com/alphaveiculos",
    "followers": 65851,
    "status": "Não contatado",
    "score": 100,
    "createdAt": "2026-07-21T18:06:56.874Z"
  },
  {
    "id": "be97cf6b",
    "storeName": "EA Motors",
    "city": "Valinhos",
    "phone": "",
    "email": "",
    "link": "https://www.eamotorsoficial.com.br/",
    "instagram": "https://www.instagram.com/eamotors",
    "followers": 36362,
    "status": "Não contatado",
    "score": 100,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "564d14bd",
    "storeName": "Zacar Veículos",
    "city": "Valinhos",
    "phone": "(19) 99209-5626",
    "email": "",
    "link": "https://zacarveiculos.com.br/",
    "instagram": "https://www.instagram.com/zacarveiculos",
    "followers": 24782,
    "status": "Não contatado",
    "score": 100,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "5c91bbf3",
    "storeName": "Sandro Veículos",
    "city": "Valinhos",
    "phone": "",
    "email": "",
    "link": "https://sandroveiculosvalinhos.com.br/",
    "instagram": "https://www.instagram.com/sandroveiculos",
    "followers": 516,
    "status": "Não contatado",
    "score": 38,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "9daa6a21",
    "storeName": "Visual Veículos",
    "city": "Valinhos",
    "phone": "",
    "email": "",
    "link": "https://www.visualveiculos.com.br/",
    "instagram": "https://www.instagram.com/visualveiculos",
    "followers": 165,
    "status": "Não contatado",
    "score": 30,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "16b248ef",
    "storeName": "Makine Motors",
    "city": "Valinhos",
    "phone": "(19) 97411-5616",
    "email": "",
    "link": "https://www.makinemotors.com.br/",
    "instagram": "https://www.instagram.com/makinemotors",
    "followers": 6444,
    "status": "Não contatado",
    "score": 84,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "72d15cfb",
    "storeName": "Concessionária Codive",
    "city": "Valinhos",
    "phone": "",
    "email": "",
    "link": "https://www.codivechevroletvalinhos.com.br/",
    "instagram": "https://www.instagram.com/concessionariacodive",
    "followers": 7753,
    "status": "Não contatado",
    "score": 90,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "d82751d4",
    "storeName": "Destaque Motors",
    "city": "Valinhos",
    "phone": "",
    "email": "",
    "link": "https://destaquemotors.com.br/",
    "instagram": "https://www.instagram.com/destaquemotors",
    "followers": 13,
    "status": "Não contatado",
    "score": 22,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "5879877b",
    "storeName": "Vaapty Valinhos",
    "city": "Valinhos",
    "phone": "(19) 99878-1422",
    "email": "",
    "link": "https://vaaptyvalinhoscentro.com/",
    "instagram": "https://www.instagram.com/vaaptyvalinhos",
    "followers": 494,
    "status": "Não contatado",
    "score": 37,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "06051e3b",
    "storeName": "Sabini Motors",
    "city": "Valinhos",
    "phone": "",
    "email": "",
    "link": "https://www.sabinimotors.com.br/",
    "instagram": "https://www.instagram.com/sabinimotors",
    "followers": 9722,
    "status": "Não contatado",
    "score": 98,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "f6d64644",
    "storeName": "Font Car Veículos",
    "city": "Valinhos",
    "phone": "(19) 3869-2066",
    "email": "",
    "link": "https://fontcarveiculos.com.br/",
    "instagram": "https://www.instagram.com/fontcarveiculos",
    "followers": 8,
    "status": "Não contatado",
    "score": 22,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "1671c7de",
    "storeName": "Julio Ferreira Veículos",
    "city": "Valinhos",
    "phone": "",
    "email": "",
    "link": "https://www.julioferreiraveiculos.com.br/",
    "instagram": "https://www.instagram.com/julioferreiraveiculos",
    "followers": 6303,
    "status": "Não contatado",
    "score": 83,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "e9c7f1f6",
    "storeName": "Will Motors",
    "city": "Valinhos",
    "phone": "(19) 99876-5432",
    "email": "",
    "link": "https://willmotors.com.br/",
    "instagram": "https://www.instagram.com/willmotors",
    "followers": 274,
    "status": "Não contatado",
    "score": 33,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "487f18f1",
    "storeName": "Hypecar Veículos",
    "city": "Valinhos",
    "phone": "(19) 99741-2895",
    "email": "vendas@hypecarveiculos.com.br",
    "link": "https://hypecarveiculos.com.br/",
    "instagram": "https://www.instagram.com/hypecarveiculos",
    "followers": 18,
    "status": "Não contatado",
    "score": 23,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "1367f3b8",
    "storeName": "Destaque Valinhos",
    "city": "Valinhos",
    "phone": "",
    "email": "",
    "link": "https://destaquemotors.com.br/",
    "instagram": "https://www.instagram.com/destaquevalinhos",
    "followers": 4852,
    "status": "Não contatado",
    "score": 75,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "70f66132",
    "storeName": "MD Motors",
    "city": "Valinhos",
    "phone": "",
    "email": "",
    "link": "https://www.mdmotors.com.br/",
    "instagram": "https://www.instagram.com/mdmotors",
    "followers": 2200,
    "status": "Não contatado",
    "score": 57,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "5220c69e",
    "storeName": "Denilson Veículos",
    "city": "Valinhos",
    "phone": "(19) 97402-2240",
    "email": "denilson@denilsonveiculos.com.br",
    "link": "https://denilsonveiculos.com.br/",
    "instagram": "https://www.instagram.com/denilsonveiculos",
    "followers": 570,
    "status": "Não contatado",
    "score": 39,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "a9c3f4ed",
    "storeName": "Movva Veículos",
    "city": "Valinhos",
    "phone": "(19) 98123-4567",
    "email": "atendimento@movvaveiculos.com.br",
    "link": "https://movvaveiculos.com.br/",
    "instagram": "https://www.instagram.com/movvaveiculos",
    "followers": 109,
    "status": "Não contatado",
    "score": 28,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "ce80719d",
    "storeName": "Independência Veículos",
    "city": "Valinhos",
    "phone": "(19) 3871-3180",
    "email": "",
    "link": "https://www.independenciaveiculos.com.br/",
    "instagram": "https://www.instagram.com/independenciaveiculos",
    "followers": 3690,
    "status": "Não contatado",
    "score": 68,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "70104d66",
    "storeName": "Faccini Veículos",
    "city": "Valinhos",
    "phone": "(19) 99180-0084",
    "email": "",
    "link": "https://www.facchiniveiculos.com.br/",
    "instagram": "https://www.instagram.com/facciniveiculos",
    "followers": 3767,
    "status": "Não contatado",
    "score": 69,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "a1a26670",
    "storeName": "Chevrolet Codive",
    "city": "Valinhos",
    "phone": "(19) 3881-9000",
    "email": "",
    "link": "https://www.codivechevroletvalinhos.com.br/",
    "instagram": "https://www.instagram.com/chevroletcodive",
    "followers": 11778,
    "status": "Não contatado",
    "score": 100,
    "createdAt": "2026-07-21T18:06:56.875Z"
  },
  {
    "id": "e31701d8",
    "storeName": "Alvorada Automóveis",
    "city": "Nova Odessa",
    "phone": "(19) 2221-7298",
    "email": "atendimento@alvoradaautomoveisno.com.br",
    "link": "https://alvoradaautomoveisno.com.br/",
    "instagram": "https://www.instagram.com/alvorada_automoveis",
    "followers": 5781,
    "status": "Não contatado",
    "score": 80,
    "createdAt": "2026-07-21T18:05:17.062Z"
  },
  {
    "id": "39d9b958",
    "storeName": "MK Veículos",
    "city": "Nova Odessa",
    "phone": "(19) 3466-5000",
    "email": "",
    "link": "https://mkveiculos.com.br/",
    "instagram": "https://www.instagram.com/mkveiculosno",
    "followers": 3501,
    "status": "Não contatado",
    "score": 67,
    "createdAt": "2026-07-21T18:05:17.062Z"
  },
  {
    "id": "ee968c28",
    "storeName": "Pantera Veículos",
    "city": "Nova Odessa",
    "phone": "(19)3466-2917",
    "email": "",
    "link": "https://www.panteraveiculos.com.br/",
    "instagram": "https://www.instagram.com/pantera.veiculos",
    "followers": 3490,
    "status": "Não contatado",
    "score": 67,
    "createdAt": "2026-07-21T18:05:17.062Z"
  },
  {
    "id": "2fb4b6a4",
    "storeName": "SR Veículos",
    "city": "Nova Odessa",
    "phone": "",
    "email": "",
    "link": "https://srcarveiculos.com.br/",
    "instagram": "https://www.instagram.com/sr_veiculos",
    "followers": 2269,
    "status": "Não contatado",
    "score": 58,
    "createdAt": "2026-07-21T18:05:17.062Z"
  },
  {
    "id": "ab66cfbd",
    "storeName": "Nova Odessa Veículos",
    "city": "Nova Odessa",
    "phone": "",
    "email": "",
    "link": "",
    "instagram": "https://www.instagram.com/novaodessaveiculos",
    "followers": 4863,
    "status": "Não contatado",
    "score": 55,
    "createdAt": "2026-07-21T18:05:17.062Z"
  },
  {
    "id": "2c1ceb41",
    "storeName": "GB Car Veículos",
    "city": "Nova Odessa",
    "phone": "(19) 99344-9988",
    "email": "",
    "link": "https://gbcarveiculos.com.br/",
    "instagram": "https://www.instagram.com/gbcar_veiculos2015",
    "followers": 986,
    "status": "Não contatado",
    "score": 45,
    "createdAt": "2026-07-21T18:05:17.062Z"
  },
  {
    "id": "718b7042",
    "storeName": "Ampelio Multimarcas",
    "city": "Nova Odessa",
    "phone": "",
    "email": "",
    "link": "",
    "instagram": "https://www.instagram.com/ampeliomultimarcas",
    "followers": 2480,
    "status": "Não contatado",
    "score": 39,
    "createdAt": "2026-07-21T18:05:17.063Z"
  },
  {
    "id": "5edf5a85",
    "storeName": "Nova Odessa Carros & Motos",
    "city": "Nova Odessa",
    "phone": "(19) 97407-4795",
    "email": "",
    "link": "https://novaodessaveiculos.com.br/",
    "instagram": "https://www.instagram.com/novaodessaveiculos",
    "followers": 2944,
    "status": "Não contatado",
    "score": 63,
    "createdAt": "2026-07-21T18:05:17.063Z"
  },
  {
    "id": "43456ddf",
    "storeName": "Jazz Veículos",
    "city": "Nova Odessa",
    "phone": "",
    "email": "",
    "link": "https://www.jazzveiculos.com.br/",
    "instagram": "https://www.instagram.com/jazzveiculos",
    "followers": 260630,
    "status": "Não contatado",
    "score": 100,
    "createdAt": "2026-07-21T18:05:17.063Z"
  },
  {
    "id": "0cf929df",
    "storeName": "Vessa Chevrolet",
    "city": "Nova Odessa",
    "phone": "(19) 3829-8000",
    "email": "",
    "link": "https://www.vessachevrolet.com.br/",
    "instagram": "https://www.instagram.com/vessachevrolet/",
    "followers": 10282,
    "status": "Não contatado",
    "score": 100,
    "createdAt": "2026-07-21T18:05:17.063Z"
  },
  {
    "id": "1c6012a2",
    "storeName": "Paschoalin Motors",
    "city": "Nova Odessa",
    "phone": "",
    "email": "",
    "link": "https://paschoalinmotors.com.br/",
    "instagram": "https://www.instagram.com/paschoalinmotors",
    "followers": 2439,
    "status": "Não contatado",
    "score": 59,
    "createdAt": "2026-07-21T18:05:17.063Z"
  },
  {
    "id": "ba7fecc5",
    "storeName": "DZM Automóveis",
    "city": "Nova Odessa",
    "phone": "(19) 3090-3345",
    "email": "",
    "link": "https://dzmautomotive.com/",
    "instagram": "https://www.instagram.com/dzm.automoveis",
    "followers": 440,
    "status": "Não contatado",
    "score": 36,
    "createdAt": "2026-07-21T18:05:17.063Z"
  },
  {
    "id": "7dfb64f4",
    "storeName": "Mônaco Veículos",
    "city": "Nova Odessa",
    "phone": "0800 000 3148",
    "email": "",
    "link": "https://www.monacoveiculos.com.br/",
    "instagram": "https://www.instagram.com/monacoveiculosnorte",
    "followers": 14814,
    "status": "Não contatado",
    "score": 100,
    "createdAt": "2026-07-21T18:05:17.063Z"
  },
  {
    "id": "09c72931",
    "storeName": "Conseg Veículos",
    "city": "Nova Odessa",
    "phone": "(19) 3466-8800",
    "email": "vendas@consegveiculos.com.br",
    "link": "https://consegveiculos.com.br/",
    "instagram": "https://www.instagram.com/consegveiculos",
    "followers": 6246,
    "status": "Não contatado",
    "score": 83,
    "createdAt": "2026-07-21T18:05:17.063Z"
  },
  {
    "id": "449f1432",
    "storeName": "Rika Motors",
    "city": "Nova Odessa",
    "phone": "(19) 99112-3434",
    "email": "",
    "link": "https://rikamotors.com.br/",
    "instagram": "https://www.instagram.com/rikamotors",
    "followers": 3483,
    "status": "Não contatado",
    "score": 67,
    "createdAt": "2026-07-21T18:05:17.063Z"
  },
  {
    "id": "489693c6",
    "storeName": "Agência de Carros",
    "city": "Nova Odessa",
    "phone": "(19) 98765-4321",
    "email": "",
    "link": "https://ousadiaveiculos.com.br/",
    "instagram": "https://www.instagram.com/ousadiaveiculos",
    "followers": 2300,
    "status": "Não contatado",
    "score": 58,
    "createdAt": "2026-07-21T18:05:17.063Z"
  },
  {
    "id": "3f1dc12f",
    "storeName": "Prime Car",
    "city": "Nova Odessa",
    "phone": "(19) 99123-8877",
    "email": "",
    "link": "https://primecar777.com.br/",
    "instagram": "https://www.instagram.com/primecar777",
    "followers": 729,
    "status": "Não contatado",
    "score": 41,
    "createdAt": "2026-07-21T18:05:17.063Z"
  },
  {
    "id": "86d8edaf",
    "storeName": "DNA Veículos",
    "city": "Nova Odessa",
    "phone": "(19) 3466-9900",
    "email": "",
    "link": "https://dnaveiculos.com.br/",
    "instagram": "https://www.instagram.com/dnaveiculos",
    "followers": 45,
    "status": "Não contatado",
    "score": 25,
    "createdAt": "2026-07-21T18:05:17.063Z"
  },
  {
    "id": "2b5c64b2",
    "storeName": "Fião Veículos",
    "city": "Nova Odessa",
    "phone": "(19) 3466-5544",
    "email": "vendas@fiaoveiculos.com.br",
    "link": "https://fiaoveiculos.com.br/",
    "instagram": "https://www.instagram.com/fiaoveiculos",
    "followers": 1598,
    "status": "Não contatado",
    "score": 51,
    "createdAt": "2026-07-21T18:05:17.063Z"
  },
  {
    "id": "d1b90289",
    "storeName": "Altomani Multimarcas",
    "city": "Hortolândia",
    "phone": "",
    "email": "",
    "link": "https://www.altomanimultimarcas.com.br",
    "instagram": "https://www.instagram.com/altomanimultimarcas",
    "followers": 6694,
    "status": "Não contatado",
    "score": 85,
    "createdAt": "2026-07-21T18:02:58.483Z"
  },
  {
    "id": "80daf1d4",
    "storeName": "Nobre Multimarcas",
    "city": "Hortolândia",
    "phone": "",
    "email": "",
    "link": "https://www.nobremultimarcashorto.com.br/",
    "instagram": "https://www.instagram.com/nobremultimarcas_",
    "followers": 14,
    "status": "Não contatado",
    "score": 22,
    "createdAt": "2026-07-21T18:02:58.484Z"
  },
  {
    "id": "c0a844be",
    "storeName": "Única Veículos",
    "city": "Hortolândia",
    "phone": "(19) 3504-8300 / 3909-0182",
    "email": "vendas@unicaveiculoshorto.com.br",
    "link": "https://unicaveiculoshorto.com.br/",
    "instagram": "https://www.instagram.com/unica.veiculos",
    "followers": 7342,
    "status": "Não contatado",
    "score": 88,
    "createdAt": "2026-07-21T18:02:58.484Z"
  },
  {
    "id": "f129a9a2",
    "storeName": "Neri Veiculos",
    "city": "Hortolândia",
    "phone": "",
    "email": "",
    "link": "https://neriveiculoshortolandia.com.br/",
    "instagram": "https://www.instagram.com/neriveiculos_hortolandia",
    "followers": 8173,
    "status": "Não contatado",
    "score": 92,
    "createdAt": "2026-07-21T18:02:58.484Z"
  },
  {
    "id": "b08304c7",
    "storeName": "Junior Cardoso Vehicles",
    "city": "Hortolândia",
    "phone": "",
    "email": "",
    "link": "https://www.veiculosjuniorcardoso.com.br/",
    "instagram": "https://www.instagram.com/juniorcardosovehicles/",
    "followers": 2480,
    "status": "Não contatado",
    "score": 59,
    "createdAt": "2026-07-21T18:02:58.484Z"
  },
  {
    "id": "6b675613",
    "storeName": "Roberto Veículos",
    "city": "Hortolândia",
    "phone": "",
    "email": "",
    "link": "https://robertoveiculos.com/",
    "instagram": "https://www.instagram.com/robertoveiculos.1",
    "followers": 3600,
    "status": "Não contatado",
    "score": 68,
    "createdAt": "2026-07-21T18:02:58.484Z"
  },
  {
    "id": "80ee5085",
    "storeName": "Mais Veículos",
    "city": "Hortolândia",
    "phone": "",
    "email": "",
    "link": "https://www.unimaisveiculos.com.br/",
    "instagram": "https://www.instagram.com/maisveiculos_hortolandia",
    "followers": 563,
    "status": "Não contatado",
    "score": 38,
    "createdAt": "2026-07-21T18:02:58.484Z"
  },
  {
    "id": "3ebe77e2",
    "storeName": "Ockner Motors",
    "city": "Hortolândia",
    "phone": "(19) 3897-1122",
    "email": "",
    "link": "https://ocknermotors.com.br/",
    "instagram": "https://www.instagram.com/ocknermotors",
    "followers": 5761,
    "status": "Não contatado",
    "score": 80,
    "createdAt": "2026-07-21T18:02:58.484Z"
  },
  {
    "id": "1595ad8b",
    "storeName": "A3 Veículos",
    "city": "Hortolândia",
    "phone": "",
    "email": "",
    "link": "https://a3veiculosoficial.com.br/",
    "instagram": "https://www.instagram.com/a3veiculos",
    "followers": 1200,
    "status": "Não contatado",
    "score": 47,
    "createdAt": "2026-07-21T18:02:58.484Z"
  },
  {
    "id": "cacf71b5",
    "storeName": "Loja de Veículos",
    "city": "Hortolândia",
    "phone": "(19) 99119-7060",
    "email": "",
    "link": "",
    "instagram": "https://www.instagram.com/lojadeveiculos",
    "followers": 1200,
    "status": "Não contatado",
    "score": 27,
    "createdAt": "2026-07-21T18:02:58.484Z"
  },
  {
    "id": "5c53d494",
    "storeName": "N5N Veículos",
    "city": "Hortolândia",
    "phone": "(19) 98877-6655",
    "email": "",
    "link": "https://n5nveiculos.com.br/",
    "instagram": "https://www.instagram.com/n5nveiculos",
    "followers": 428,
    "status": "Não contatado",
    "score": 36,
    "createdAt": "2026-07-21T18:02:58.484Z"
  },
  {
    "id": "060576cf",
    "storeName": "Vaapty Hortolândia",
    "city": "Hortolândia",
    "phone": "",
    "email": "",
    "link": "https://vaapty.com.br/",
    "instagram": "https://www.instagram.com/vaaptyhortolandia",
    "followers": 2177,
    "status": "Não contatado",
    "score": 57,
    "createdAt": "2026-07-21T18:02:58.484Z"
  }
];
